services:
  localaiapivscode:
    image: localaiapivscode
    build:
      context: vscode-extension
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
